### ISSUE TITLE
How to activate Check?

### ISSUE THREAD

**Issue by chaapp87** [JensKuehnel/fail2ban-check-mk#1]
Hi Jens,

great work, I'm really interested in the plugin.
I installed the mkp file and configured a rule in Service Checks.
How do I activate a check for a host?
Do I have to bake a new agent? I don't find a bakery rule.

Many thanks in advance!
Roland

**Comment by JensKuehnel** [comment]
Hi @chaapp87,

I use the raw edition of checkmk and put my agent onto my machines with ansible. 
That is the reason I forgot to create a bakery rule. 
Do you know how to write it? If yes, please do. I don't know when I have time to read the docu how to create the bakery rule.

CU
Jens

**Comment by JensKuehnel** [comment]
Hi @chaapp87 ,
I added an initial support for the bakery, please try 1.9.0.

CU
Jens

**Comment by JensKuehnel** [comment]
Hi, I will resurrect thie plugin und will release a new version today or tomorrow, with support 2.2 and 2.3.
