### ISSUE TITLE
check_mk 2.2 - Error: name 'Tuple' is not defined

### ISSUE THREAD

**Issue by nicoh88** [JensKuehnel/fail2ban-check-mk#13]
Hi @JensKuehnel,

danke für deine Weiterentwicklung des Fail2Ban-CMK-Plugins mit WATO Integration.
Leider hat sich mit 2.2 etwas an der Integration der Plugins geändert.

Ich bekomme seit dem Update folgenden Fehlermeldung `Internal error: name 'Tuple' is not defined`. Auch eine Veränderung der HOST- oder SERVICE-Konfiguration ist aktuell nicht möglich, da immer diese Meldung erscheint.

**Traceback beim Aufrufen der WATO Konfiguration:**

```
  File "/omd/sites/mon/lib/python3/cmk/gui/wsgi/applications/checkmk.py", line 192, in _process_request
    resp = page_handler()
  File "/omd/sites/mon/lib/python3/cmk/gui/wsgi/applications/utils.py", line 107, in _call_auth
    func()
  File "/omd/sites/mon/lib/python3/cmk/gui/pages.py", line 187, in wrapper
    return hc().handle_page()
  File "/omd/sites/mon/lib/python3/cmk/gui/pages.py", line 51, in handle_page
    self.page()
  File "/omd/sites/mon/lib/python3/cmk/gui/pages.py", line 146, in <lambda>
    "page": lambda self: self._wrapped_callable[0](),
  File "/omd/sites/mon/lib/python3/cmk/gui/wato/page_handler.py", line 87, in page_handler
    mode_instance = mode_registry.get(current_mode, ModeNotImplemented)()
  File "/omd/sites/mon/lib/python3/cmk/gui/wato/pages/rulesets.py", line 783, in __init__
    super().__init__()
  File "/omd/sites/mon/lib/python3/cmk/gui/plugins/wato/utils/base_modes.py", line 31, in __init__
    self._from_vars()
  File "/omd/sites/mon/lib/python3/cmk/gui/wato/pages/rulesets.py", line 824, in _from_vars
    self._valuespec = self._rulespec.valuespec
  File "/omd/sites/mon/lib/python3/cmk/gui/watolib/rulespecs.py", line 348, in valuespec
    return self._valuespec()
  File "/omd/sites/mon/lib/python3/cmk/gui/watolib/rulespecs.py", line 738, in _rulespec_valuespec
    return _wrap_valuespec_in_timeperiod_valuespec(self._parameter_valuespec())
  File "<string>", line 41, in _parameter_valuespec_fail2ban
```

Eventuell findest du mal ein paar Minuten Zeit und kannst dich dem Problem annehmen.

Vielen Dank und viele Grüße aus Oberfranken,
Nico

**Comment by max1404** [comment]
@JensKuehnel Problem besteht leider weiterhin. Wird bestimmt nur eine Kleinigkeit sein.

Das Problem erscheint auch, wenn man die "Service monitoring rules" > "Number of fail2ban Banned/Failed IPs" bearbeiten oder anlegen möchte.

**Comment by Scheintnurso88** [comment]
Seit check-mk 2.2.0  wird Tuple nicht mehr in lib/python3/cmk/gui/wato/__init__.py importiert, also muß das jetzt in fail2ban_parameters.py gemacht werden:

```
diff -uw --color -r 2.2.0/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py old/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py
--- old/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py    2023-08-13 11:19:50.549717156 +0200
+++ 2.2.0/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py  2023-09-24 11:13:04.249449518 +0200
@@ -22,7 +22,6 @@
     Dictionary,
     Integer,
     TextAscii,
+    Tuple,
)

from cmk.gui.plugins.wato import (
```

**Comment by max1404** [comment]
> Seit check-mk 2.2.0 wird Tuple nicht mehr in lib/python3/cmk/gui/wato/**init**.py importiert, also muß das jetzt in fail2ban_parameters.py gemacht werden:
> 
> ```
> diff -uw --color -r 2.2.0/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py old/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py
> --- old/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py    2023-08-13 11:19:50.549717156 +0200
> +++ 2.2.0/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py  2023-09-24 11:13:04.249449518 +0200
> @@ -22,7 +22,6 @@
>      Dictionary,
>      Integer,
>      TextAscii,
> +    Tuple,
> )
> 
> from cmk.gui.plugins.wato import (
> ```

Super. Danke. Habe ich geändert. Läuft, habe noch ein `cmk-update-config -v` gebraucht.

Aber jetzt fehlt das WATO-Menü zum Konfigurieren der Schwellwerte. Beim Konfigurieren eines Jails aus dem "Discover Service" kommt:

`{'key': 'static_checks:fail2ban',  'self': <cmk.gui.watolib.rulespecs.RulespecRegistry object at 0x7fb389090350>}
`
```
  File "/omd/sites/mon/lib/python3/cmk/gui/wsgi/applications/checkmk.py", line 183, in _process_request
    resp = page_handler()
  File "/omd/sites/mon/lib/python3/cmk/gui/wsgi/applications/utils.py", line 107, in _call_auth
    func()
  File "/omd/sites/mon/lib/python3/cmk/gui/pages.py", line 187, in wrapper
    return hc().handle_page()
  File "/omd/sites/mon/lib/python3/cmk/gui/pages.py", line 51, in handle_page
    self.page()
  File "/omd/sites/mon/lib/python3/cmk/gui/pages.py", line 146, in <lambda>
    "page": lambda self: self._wrapped_callable[0](),
  File "/omd/sites/mon/lib/python3/cmk/gui/wato/page_handler.py", line 100, in page_handler
    _wato_page_handler(current_mode, mode_instance)
  File "/omd/sites/mon/lib/python3/cmk/gui/wato/page_handler.py", line 156, in _wato_page_handler
    mode.handle_page()
  File "/omd/sites/mon/lib/python3/cmk/gui/plugins/wato/utils/base_modes.py", line 177, in handle_page
    return self.page()
  File "/omd/sites/mon/lib/python3/cmk/gui/wato/pages/object_parameters.py", line 123, in page
    self._show_service_info(all_rulesets=all_rulesets, service_result=service_result)
  File "/omd/sites/mon/lib/python3/cmk/gui/wato/pages/object_parameters.py", line 269, in _show_service_info
    rulespec = rulespec_registry["static_checks:" + checkgroup]
  File "/omd/sites/mon/lib/python3/cmk/utils/plugin_registry.py", line 66, in __getitem__
    return self._entries.__getitem__(key)
```

Gruß Max

**Comment by Scheintnurso88** [comment]
On Tue, Sep 26, 2023 at 02:45:34AM -0700, max1404 wrote:
> > Seit check-mk 2.2.0 wird Tuple nicht mehr in lib/python3/cmk/gui/wato/**init**.py importiert, also muß das jetzt in fail2ban_parameters.py gemacht werden:
> > 
> > ```
> > diff -uw --color -r 2.2.0/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py old/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py
> > --- old/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py    2023-08-13 11:19:50.549717156 +0200
> > +++ 2.2.0/local/share/check_mk/web/plugins/wato/fail2ban_parameters.py  2023-09-24 11:13:04.249449518 +0200
> > @@ -22,7 +22,6 @@
> >      Dictionary,
> >      Integer,
> >      TextAscii,
> > +    Tuple,
> > )
> > 
> > from cmk.gui.plugins.wato import (
> > ```
> 
> Super. Danke. Habe ich geändert. Aber jetzt bekomme ich folgenden Fehler:
> 
> ```
> {'key': 'static_checks:fail2ban',
>  'self': <cmk.gui.watolib.rulespecs.RulespecRegistry object at 0x7fb38908c250>}
> ```
> 
> ```
>   File "/omd/sites/mon/lib/python3/cmk/gui/wsgi/applications/checkmk.py", line 183, in _process_request
>     resp = page_handler()
>   File "/omd/sites/mon/lib/python3/cmk/gui/wsgi/applications/utils.py", line 107, in _call_auth
>     func()
>   File "/omd/sites/mon/lib/python3/cmk/gui/pages.py", line 187, in wrapper
>     return hc().handle_page()
>   File "/omd/sites/mon/lib/python3/cmk/gui/pages.py", line 51, in handle_page
>     self.page()
>   File "/omd/sites/mon/lib/python3/cmk/gui/pages.py", line 146, in <lambda>
>     "page": lambda self: self._wrapped_callable[0](),
>   File "/omd/sites/mon/lib/python3/cmk/gui/wato/page_handler.py", line 100, in page_handler
>     _wato_page_handler(current_mode, mode_instance)
>   File "/omd/sites/mon/lib/python3/cmk/gui/wato/page_handler.py", line 156, in _wato_page_handler
>     mode.handle_page()
>   File "/omd/sites/mon/lib/python3/cmk/gui/plugins/wato/utils/base_modes.py", line 177, in handle_page
>     return self.page()
>   File "/omd/sites/mon/lib/python3/cmk/gui/wato/pages/object_parameters.py", line 123, in page
>     self._show_service_info(all_rulesets=all_rulesets, service_result=service_result)
>   File "/omd/sites/mon/lib/python3/cmk/gui/wato/pages/object_parameters.py", line 269, in _show_service_info
>     rulespec = rulespec_registry["static_checks:" + checkgroup]
>   File "/omd/sites/mon/lib/python3/cmk/utils/plugin_registry.py", line 66, in __getitem__
>     return self._entries.__getitem__(key)
> ```
> 
> Hast du es bei dir am laufen und getestet?
> 
> Gruß Max

Es läuft in 4 verschiedenen check-mk Installationen, bei denen ich
bisher (p8 -> p9 -> p10) vor dem

  omd stop XX;omd update XX;omd start XX

ein

  mkp disable fail2ban

und danach ein

  mkp enable fail2ban

ausgeführt habe.

Ich habe nur Obiges (Tuple,) eingefügt und danach die betroffenen
Hosts über 

Setup->Hosts->(Host auswählen) und dann Run service discovey

gestartet; es war immer notwendig neben einem Rescan auch noch einen
Service über Move to undecided service zu deaktiviere und wieder
aktiviere damit man dann über pendig changes den Host mit allen
Services neu generirert.


Einmal hat das nicht geholfen, da habe ich dann omd gestoppt und
wieder gestartet.

systemctl stop omd
systemctl start omd

Ich hänge meine fail2ban_parameters.py mal an.

**Comment by max1404** [comment]
Jetzt hat es geklappt. Danke.

**Comment by nicoh88** [comment]
@Scheintnurso88 Ich bedanke mich auch!!

Machst du noch ein PR für @JensKuehnel? Dann veröffentlicht er vielleicht eine neue Version.

**Comment by Scheintnurso88** [comment]
Das hat schon jemand am 8 April behoben:

Various improvements #12 
https://github.com/JensKuehnel/fail2ban-check-mk/pull/12/commits/3895207a5d6e266f6b0aad3e0312f6fbd866655a

**Comment by JensKuehnel** [comment]
Hi, Ich habe leider diesen Check etwas schleifen lassen. Ich werde noch heute oder morgen eine Version für 2.2 und 2.3 releasen.
