### ISSUE TITLE
MKP on exchange.checkmk.com out of date

### ISSUE THREAD

**Issue by robin-checkmk** [JensKuehnel/fail2ban-check-mk#3]
The MKP file on the exchange is out of date and in a broken state.
Just leaving this here as a reminder.

**Comment by JensKuehnel** [comment]
hi @robin-tribe29,
Released a new version 1.9.0 and uploaded it to the exchange.
What is the a best practice to automatically create the mkp out of the git tree? I created a copy-to-mk now to simplify the rollout to check_mk directly. I will create one to create the mkp, but maybe there is a solution already and I simply could not find it?
CU
Jens

**Comment by robin-checkmk** [comment]
Awesome, thanks for the update! I will go and test the plugin as soon as possible and report back if you like. But feel free to close this issue, my immediate goal is achieved. :)

Regarding the automatic build of MKPs: We are working on something, but I cannot share details yet. It will also not be ready shortly, so for now there is nothing official. But we will certainly announce this, once it is ready.
