### ISSUE TITLE
no "jail" services detected

### ISSUE THREAD

**Issue by hoegerl** [JensKuehnel/fail2ban-check-mk#4]
Hi,

i installed the latest plugin from the exchange 1.8.9 via WATO (also tried manually).
I then updated the code of the plugin to reflect your github code (the capital letters $JAILS and the SC2600 thing).

`#!/bin/sh
if [ -x /usr/bin/fail2ban-client ]; then
echo '<<<fail2ban>>>'
jails="$(/usr/bin/fail2ban-client status | grep "Jail list" | sed -e 's/.*://' -e 's/,//g')"
        echo "Detected jails: $JAILS"
        for jail in $jails
        do
                /usr/bin/fail2ban-client status $jail
        done
fi`

I copied the agent-plugin to my agent plugin-folder.
`~/local/share/check_mk/agents -> /usr/lib/check_mk_agent/plugins`

The "<<<fail2ban>>>" info is showing in the agent output.
<<<fail2ban>>>
Detected jails:
Status for the jail: sshd
|- Filter
| |- Currently failed: 0
| |- Total failed: 0
| `- File list: /var/log/auth.log
`- Actions
|- Currently banned: 0
|- Total banned: 0
`- Banned IP list:
Status for the jail: webmin-auth
|- Filter
| |- Currently failed: 0
| |- Total failed: 0
| `- File list: /var/log/auth.log
`- Actions
|- Currently banned: 0
|- Total banned: 0
`- Banned IP list:

The problem is that no new service is detected for the 2 jails i have active.
I also created a "default" fail2-ban rule in the service checks (only setting warn/crit levels), but still no "jail xxx" service is showing up.

Can you help me out or point me in a direction to solve this?
I'm using checkmk free edition in version 2.0.0p16

Thx for the plugin!
cheers
Felix

**Comment by JensKuehnel** [comment]
Hi Felix,
sorry for the delay in answering.

Could you tell me some more about you system. OS, Distro fail2ban version etc.

Also please paste  the output of the following command  as code into the issue:
`/usr/bin/fail2ban-client status`

The line "Detected jails" at the beginning should not be empty, when there are jails shown later.
CU
Jens

**Comment by hoegerl** [comment]
Hi Jens,
it turned out that something with my checkmk-server is wrong.
After a reboot of the checkmk-server the jail-services are detected as expected.

cheers
Felix
