### ISSUE TITLE
Exception: name 'perfometer_logarithmic' is not defined

### ISSUE THREAD

**Issue by nuggie** [JensKuehnel/fail2ban-check-mk#5]
Hi,

I'm running cmk 2.0.0p13 (CRE) and the Perf-O-Meter of the fail2ban checks give me the following error:

![image](https://user-images.githubusercontent.com/4766589/150505371-77a066c5-3ef5-4d59-9e4e-b135428d9b6b.png)

**Comment by lucky4ever2** [comment]
Hi,
ich habe das gleiche Problem mit 2.0.0p21 (CEE).

**Comment by JensKuehnel** [comment]
Hi, I will resurrect thie plugin und will release a new version today or tomorrow, with support 2.2 and 2.3.
