### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by bunzladi** [JensKuehnel/fail2ban-check-mk#8]
Hello together
My plugin is not working. 
I downloaded the MPK file with this link and inserted it into CheckMK like this: https://exchange.checkmk.com/p/fail2ban-2

![image](https://user-images.githubusercontent.com/92428604/166432021-9bb724ee-3ca5-483f-b8c4-4023b24d2dd0.png)

Then I configured it like this: 

![image](https://user-images.githubusercontent.com/92428604/166432083-67fe72c4-765c-4ee9-b082-c545890f301e.png)

![image](https://user-images.githubusercontent.com/92428604/166432116-40b79e44-a3a5-4ef6-8b80-71ec0af246c9.png)

Then in Check MK it says Unknown. The Fail2Ban works correctly on the host (Ubuntu 20.04.4 LTS) and I also tried it with a newly set up Ubuntu host. 

Thanks in advance for the help.
Kind regards

**Comment by Operator873** [comment]
I haven't used the mkp package, but cloning this repo and executing the shell script as the omd user worked just fine for me. The only gotcha point would be if your checkmk server is not the server running fail2ban. In which case, scp this file: `/omd/sites/<your_omd_site>/local/share/check_mk/agents/plugins/fail2ban` to the fail2ban server and place it in the `/usr/lib/check_mk_agent/plugins/` folder. 

Verify by running `check_mk_agent` on the fail2ban server and fail2ban info should be at the end of the output.

**Comment by bunzladi** [comment]
Thanks for your reply, but that didn't work for us. 
fyi: We use the CheckMK appliance

**Comment by JensKuehnel** [comment]
Hi, I will resurrect thie plugin und will release a new version today or tomorrow, with support 2.2 and 2.3.

**Comment by JensKuehnel** [comment]
Will be fixed with help from #CMKConf10
